### ISSUE TITLE
Wtf

### ISSUE THREAD

**Issue by fixedelineation** [xia256/discussions3#13]
https://discussions.app/p/jamez/7s91wkpcis9m/_

**Comment by zen-wq** [comment]
This looks like what I'm getting when trying to run my instance:
```
$ npm run serve

> discussions3@0.1.0 serve
> npm run generate-api && vue-cli-service serve


> discussions3@0.1.0 generate-api
> npx babel-node --max-old-space-size=4096 --config-file ./src/server/babel.config.js ./src/server/api/generate.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '../config.json'
Require stack:
- /home/naryl/work/discussions3/src/server/api/objects/PostObject.js
- /home/naryl/work/discussions3/src/server/api/objects/index.js
- /home/naryl/work/discussions3/src/server/gateways/ActionGatewayController.js
- /home/naryl/work/discussions3/src/server/gateways/index.js
- /home/naryl/work/discussions3/src/server/api/generate.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object. (/home/naryl/work/discussions3/src/server/api/objects/PostObject.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/home/naryl/work/discussions3/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (/home/naryl/work/discussions3/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/naryl/work/discussions3/src/server/api/objects/PostObject.js',
    '/home/naryl/work/discussions3/src/server/api/objects/index.js',
    '/home/naryl/work/discussions3/src/server/gateways/ActionGatewayController.js',
    '/home/naryl/work/discussions3/src/server/gateways/index.js',
    '/home/naryl/work/discussions3/src/server/api/generate.js'
  ]
}
```

**Comment by xia256** [comment]
@zen-wq I've opened #15 which should be closed by the end of this week with proper build instructions as well as configuration to allow a local ran interface to connect to our backend.
